included:
- .
excluded:
- Carthage
- Pods

opt_in_rules:

# 無効にするルール
disabled_rules:
- colon
- trailing_whitespace
- nesting
- multiple_closures_with_trailing_closure # 複数のクロージャーの場合でも、trailing closureを利用したいため
- empty_enum_arguments # enumの引数を省略したいため

line_length:
  warning: 120
  error: 300

type_body_length:
  warning: 200
  error: 350

function_body_length:
  warning: 100
  error: 120

identifier_name:
  allowed_symbols: "_"
  min_length:
    error: 2
  max_length:
    error: 40
  excluded:
    - id
    - URL
    - vm

reporter: "xcode"
